default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER")  %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>

development:
  primary:
    <<: *default
    database: umeassess_development
  # secondary:
  #   <<: *default
  #   database: redei_development
test:
  <<: *default
  database: umeassess_test

production:
  <<: *default
  database: umeassess_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
